### ISSUE TITLE
Port to Wireless Kinesis BLE board

### ISSUE THREAD

**Issue by sysdevmike** [mattvilim/FeatherCtrl#1]
Hope you don't mind but I tried to do a port of your firmware to my BLE board. 

I got it working for the most part, except certain keys (such as arrow keys) seem to give me weird key codes.

For example the left key has the following code  ` [(int)Scancode::Left] = 0x50` but...

`(int)key;  // 90`
`(int)info.scancode)    // -57`
`report.keycode[0] // 96`

Thanks for posting this up by the way, your firmware is way more elegant than the procedural hack I cobbled together.

**Comment by sysdevmike** [comment]
Fixed it, had to cast HID::Scancode to uint8_t.

**Comment by mattvilim** [comment]
Got it, I was just writing up a response... :)

BTW, I'm in the process of adding wired USB support with the nrf52840 if you're interested; it's nice to be able to function both wired and wireless. As a part of that, I'm adding different HID backends, one of which is a terminal interface to allow you to run the firmware directly on the computer. That should make it much easier to debug logic bugs without having to flash the board and potentially brick my only keyboard.

As is, it's very annoying working on the keyboard when I don't have my second Kinesis around for recovery.

**Comment by sysdevmike** [comment]
Yeah, that would be awesome. I had the same idea, even built a board with nrf52840. But after taking a look at the nordic SDK (and not understanding a thing), and finding out that it consumed twice as much power, I scrapped the idea of me being able to do it. Agreed with only having one keyboard using it to work on itself. Recently bought a beat up Advantage 1 for that scenario exactly.

By the way, while I was debugging the weird scancode issue above, I attempted to follow along your code. It's inspiring work. The firmware I previously adapted, detected one key event per loop, and used loop counts to handle debouncing. You can imagine the delays. But you separate matrix scanning, keymap updates and HID sending, with loops in each step, but achieve delay on par with a USB keyboard. Thanks for sharing!
